apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-grafana2
  namespace: monitoring
spec:
  dataSource:
    name: loki-grafana-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi