apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
      meta.helm.sh/release-name: prometheus
      meta.helm.sh/release-namespace: monitoring
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: disk-csi-driver.mks.ycloud.io
      volume.kubernetes.io/selected-node: cl187l41odr0r6io6qd1-eqyz
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.10.1
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager2
  namespace: monitoring
spec:
  dataSource:
    name: prometheusalertmanager-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi