apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: disk-csi-driver.mks.ycloud.io
    volume.kubernetes.io/selected-node: cl187l41odr0r6io6qd1-eqyz
  creationTimestamp: "2022-03-18T14:38:23Z"
  finalizers:
  - kubernetes.io/pvc-protection
  - snapshot.storage.kubernetes.io/pvc-as-source-protection
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.10.1
    component: server
    heritage: Helm
    release: prometheus
  name: prometheus-server
  namespace: monitoring
  resourceVersion: "70328213"
  uid: b543cb1e-856f-4b2d-9a29-e8717190ccbd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: yc-network-hdd
  volumeMode: Filesystem
  volumeName: pvc-b543cb1e-856f-4b2d-9a29-e8717190ccbd
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
