apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 
spec:
  dataSource:
    name: prometheusalertmanager-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi