apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-04-26T11:57:10Z"
  generateName: client-stable-86586f5d98-
  labels:
    app.kubernetes.io/instance: client-stable
    app.kubernetes.io/name: client
    pod-template-hash: 86586f5d98
  name: client-stable-86586f5d98-t5jh7
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: client-stable-86586f5d98
    uid: 0f03f07b-dbe3-4219-be8e-04283976b8cd
  resourceVersion: "23759474"
  uid: c1129f3e-87dd-487b-95cb-26afd76fc8f6
spec:
  containers:
  - image: registry.gitlab.com/zefir-projects/saharok-monorepo/client:0.1.04dece52
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: client
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7mxx9
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: regcred
  nodeName: cl187l41odr0r6io6qd1-udem
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: client-stable
  serviceAccountName: client-stable
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-7mxx9
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-04-26T11:57:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-04-26T11:57:50Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-04-26T11:57:50Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-04-26T11:57:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a679588c8024850f56554680fb70323857a9b87fdc3a5f96cc08bf38807f504b
    image: registry.gitlab.com/zefir-projects/saharok-monorepo/client:0.1.04dece52
    imageID: docker-pullable://registry.gitlab.com/zefir-projects/saharok-monorepo/client@sha256:81596f1ef84bb2e1e2247dc8bcc3eca8dbfeed83b77b27d80a7d6032cb7c6aa4
    lastState: {}
    name: client
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-04-26T11:57:11Z"
  hostIP: 10.128.0.35
  phase: Running
  podIP: 10.112.128.25
  podIPs:
  - ip: 10.112.128.25
  qosClass: Guaranteed
  startTime: "2022-04-26T11:57:10Z"
