apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-10-25T10:14:42Z"
  labels:
    app: cadvisor
    controller-revision-hash: 6c6d59d9d4
    name: cadvisor
    pod-template-generation: "1"
  name: cadvisor-dwl9q
  namespace: cadvisor
  resourceVersion: "412371"
  uid: 3d509e82-9e80-4dc3-bea3-19f234bb355f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.152.183.25
  clusterIPs:
  - 10.152.183.25
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31986
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cadvisor
    controller-revision-hash: 6c6d59d9d4
    name: cadvisor
    pod-template-generation: "1"
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 46.30.43.68