apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"alertmanager-discord","namespace":"monitoring","creationTimestamp":null,"labels":{"app":"alertmanager-discord"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"alertmanager-discord"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"alertmanager-discord"}},"spec":{"containers":[{"name":"alertmanager-discord","image":"quay.io/werstatyw/alertmanager-discord:0.1.0","ports":[{"containerPort":9094}],"resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: "2022-04-21T06:58:35Z"
  generation: 1
  labels:
    app: alertmanager-discord
  name: alertmanager-discord
  namespace: monitoring
  resourceVersion: "21652596"
  uid: a58ca318-b4cc-48bb-b3ef-adb232b74aa7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alertmanager-discord
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alertmanager-discord
    spec:
      containers:
      - image: quay.io/werstatyw/alertmanager-discord:0.1.1
        imagePullPolicy: IfNotPresent
        name: alertmanager-discord
        ports:
        - containerPort: 9094
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-04-21T06:58:41Z"
    lastUpdateTime: "2022-04-21T06:58:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-04-21T06:58:35Z"
    lastUpdateTime: "2022-04-21T06:58:41Z"
    message: ReplicaSet "alertmanager-discord-575b44c698" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
