apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alertmanager-discord
  name: alertmanager-discord
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-discord2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alertmanager-discord
    spec:
      containers:
      - image: quay.io/werstatyw/alertmanager-discord:0.1.1
        name: alertmanager-discord
        ports:
        - containerPort: 9094
        resources: {}
status: {}
