apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-03-18T14:36:15Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: loki-grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 8.3.6
    helm.sh/chart: grafana-6.22.0
  name: loki-grafana
  namespace: monitoring
  resourceVersion: "8034579"
  uid: 1b5deb3c-112d-418e-b1c0-84e946c86023
spec:
  clusterIP: 10.96.129.169
  clusterIPs:
  - 10.96.129.169
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port-1
    nodePort: 31968
    port: 80
    protocol: TCP
    targetPort: 80
  - name: port-2
    nodePort: 32599
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: loki-grafana
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 217.28.230.230
