apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner-secret
  namespace: gitlab-runner
type: Opaque
data:
  runner-registration-token: "R1IxMzQ4OTQxYk4tUEh6Z204ek1yeDFzTi16Vno=" #base64 encoded registration token
  runner-token: ""