apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: mongodb
  name: allow-port-forward-in-mongodb
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create"]
