controller:
  stats:
    enable: True
  metrics:
    port: 10254
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels: 
        heritage: Helm
        release: prometheus-prod
      namespace: "monitoring"
      scrapeInterval: 5s